Create an empty data dictionary with keys: name, roll, address, age where all the keys store a list of values. Fill in 10 valid data samples in the dictionary asking from the user. Then convert the dictionary to dataframe and add a new column to the dataframe called ‘category’. If the age is less than or equal to 15 then, category will be ‘Junior’, if its between 15 to 25(included), category will be ‘Mid’ and for the rest - category will be ‘Senior’. Display the dataframe. Calculate the average age and most frequent category

In [7]:
import pandas as pd

In [5]:
data = {
    'name': [],
    'roll': [],
    'address': [],
    'age': []
}

In [6]:
for i in range(2):
    print(f"Enter details for {i + 1} student: ")
    data['name'].append(input("Enter Name"))
    data['roll'].append(int(input("Enter roll")))
    data['address'].append(input("Enter address"))
    data['age'].append(int(input("Enter age")))

Enter details for 1 student:
Enter details for 2 student:

In [9]:
df = pd.DataFrame(data)
df

   name  roll     address  age
0  arun    10       thimi   25
1   abr    12  lokanthali   24

In [10]:
def assign_category(age):
    if age <= 15:
        return 'Junior'
    elif age > 25:
        return 'Senior'
    else:
        return 'Mid'
    
df['Category'] = df['age'].apply(assign_category)
df

   name  roll     address  age Category
0  arun    10       thimi   25      Mid
1   abr    12  lokanthali   24      Mid

## calcualte average age

In [18]:
average_age = df['age'].mean()
average_age.item()

24.5

## Most frequent category

In [13]:
most_freq = df['Category'].mode()[0]
most_freq

'Mid'