Task 1

In [4]:
import pandas as pd

data = {
'Product': ['Laptop', 'Shirt', 'Smartphone', 'Shoes', 'Headphones', 'Watch'],
'Price': [999.99, 29.99, 599.99, 89.99, 199.99, 49.99],
'Category': ['Electronics', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion']
}

df=pd.DataFrame(data)
# Filter the DataFrame to only include rows where the Price is greater than $50
df = df[df['Price'] > 50]
# Filter the resulting DataFrame to only include rows where the Category is either "Electronics" or "Fashion"
df= df[df['Category'].isin(['Electronics', 'Fashion'])]
# Print the resulting DataFrame
print(df)

      Product   Price     Category
0      Laptop  999.99  Electronics
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics

Task 2

Merge the two DataFrames on the CustomerID column
Print the resulting DataFrame
Create the first sample DataFrame df1
data1 = { 'CustomerID': [1, 2, 3, 4], 'Name': ['John Doe', 'Jane Smith', 'Alice Johnson', 'Bob Brown'], 'Address': ['123 Elm St', '456 Oak St', '789 Pine St', '101 Maple St'] }

Create the second sample DataFrame df2
data2 = { 'CustomerID': [1, 2, 1, 3],
'OrderDate': ['2024-01-01', '2024-01-05', '2024-01-10', '2024-01-15'],
'TotalAmount': [100.50, 200.75, 150.25, 300.00]
}

In [6]:
import pandas as pd
data1 = {
    'CustomerID': [1, 2, 3, 4],
    'Name': ['John Doe', 'Jane Smith', 'Alice Johnson', 'Bob Brown'],
    'Address': ['123 Elm St', '456 Oak St', '789 Pine St', '101 Maple St']
}
df1 = pd.DataFrame(data1)
df1

   CustomerID           Name       Address
0           1       John Doe    123 Elm St
1           2     Jane Smith    456 Oak St
2           3  Alice Johnson   789 Pine St
3           4      Bob Brown  101 Maple St

In [7]:

data2 = {
    'CustomerID': [1, 2, 1, 3],
    'OrderDate': ['2024-01-01', '2024-01-05', '2024-01-10', '2024-01-15'],
    'TotalAmount': [100.50, 200.75, 150.25, 300.00]
}
df2 = pd.DataFrame(data2)
df2

   CustomerID   OrderDate  TotalAmount
0           1  2024-01-01       100.50
1           2  2024-01-05       200.75
2           1  2024-01-10       150.25
3           3  2024-01-15       300.00

In [10]:
pd.merge(df1, df2, on='CustomerID')

   CustomerID           Name      Address   OrderDate  TotalAmount
0           1       John Doe   123 Elm St  2024-01-01       100.50
1           1       John Doe   123 Elm St  2024-01-10       150.25
2           2     Jane Smith   456 Oak St  2024-01-05       200.75
3           3  Alice Johnson  789 Pine St  2024-01-15       300.00

TASK 3:
Group the DataFrame by the Region column
Calculate the total Sales for each region
Calculate the average Sales for each region
Print the resulting DataFrame
Create a sample DataFrame
data = {
'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
'Sales': [150, 200, 250, 300, 350, 400, 450, 500],
'Quarter': ['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2', 'Q2']
}

In [11]:
import pandas as pd
# Step 1: Create the sample DataFrame
data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Sales': [150, 200, 250, 300, 350, 400, 450, 500],
    'Quarter': ['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2', 'Q2']
}
df = pd.DataFrame(data)
df

  Region  Sales Quarter
0  North    150      Q1
1  South    200      Q1
2   East    250      Q1
3   West    300      Q1
4  North    350      Q2
5  South    400      Q2
6   East    450      Q2
7   West    500      Q2

In [12]:
grouped = df.groupby('Region')

In [13]:
summary=grouped['Sales'].agg(Total_Sales='sum',Average_Sales='mean',Max_Sales='max',Min_Sales='min').reset_index()
print(summary)

  Region  Total_Sales  Average_Sales  Max_Sales  Min_Sales
0   East          700          350.0        450        250
1  North          500          250.0        350        150
2  South          600          300.0        400        200
3   West          800          400.0        500        300