### TASK 1:

1. Filter the DataFrame to only include rows where the Price is greater than $50
2. Filter the resulting DataFrame to only include rows where the Category is either "Electronics" or "Fashion"
3. Print the resulting DataFrame

### Create the sample DataFrame dataframe
data = {  
    'Product': ['Laptop', 'Shirt', 'Smartphone', 'Shoes', 'Headphones', 'Watch'],  
    'Price': [999.99, 29.99, 599.99, 89.99, 199.99, 49.99],  
    'Category': ['Electronics', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion']  
}

In [43]:
import pandas as pd

In [44]:
data = {  
    'Product': ['Laptop', 'Shirt', 'Smartphone', 'Shoes', 'Headphones', 'Watch'],  
    'Price': [999.99, 29.99, 599.99, 89.99, 199.99, 49.99],  
    'Category': ['Electronics', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion']  
}

df = pd.DataFrame(data)
df

      Product   Price     Category
0      Laptop  999.99  Electronics
1       Shirt   29.99      Fashion
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics
5       Watch   49.99      Fashion

In [45]:
# 1.
df = df[df['Price']>50]
df

      Product   Price     Category
0      Laptop  999.99  Electronics
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics

In [46]:
# 2.

df = df[(df['Category'] == 'Electronics') | (df['Category'] == 'Fashion')]
df

      Product   Price     Category
0      Laptop  999.99  Electronics
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics

In [47]:
df

      Product   Price     Category
0      Laptop  999.99  Electronics
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics

### TASK 2:

1. Merge the two DataFrames on the CustomerID column
2. Print the resulting DataFrame
   
### Create the first sample DataFrame df1
data1 = {
    'CustomerID': [1, 2, 3, 4],
    'Name': ['John Doe', 'Jane Smith', 'Alice Johnson', 'Bob Brown'],
    'Address': ['123 Elm St', '456 Oak St', '789 Pine St', '101 Maple St']
}

### Create the second sample DataFrame df2
data2 = {
    'CustomerID': [1, 2, 1, 3],  
    'OrderDate': ['2024-01-01', '2024-01-05', '2024-01-10', '2024-01-15'],  
    'TotalAmount': [100.50, 200.75, 150.25, 300.00]  
}

In [48]:
### Create the first sample DataFrame df1
data1 = {
    'CustomerID': [1, 2, 3, 4],
    'Name': ['John Doe', 'Jane Smith', 'Alice Johnson', 'Bob Brown'],
    'Address': ['123 Elm St', '456 Oak St', '789 Pine St', '101 Maple St']
}

### Create the second sample DataFrame df2
data2 = {
    'CustomerID': [1, 2, 1, 3],  
    'OrderDate': ['2024-01-01', '2024-01-05', '2024-01-10', '2024-01-15'],  
    'TotalAmount': [100.50, 200.75, 150.25, 300.00]  
}

In [49]:
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [50]:
merged_df = pd.merge(df1, df2, on='CustomerID')
merged_df

   CustomerID           Name      Address   OrderDate  TotalAmount
0           1       John Doe   123 Elm St  2024-01-01       100.50
1           1       John Doe   123 Elm St  2024-01-10       150.25
2           2     Jane Smith   456 Oak St  2024-01-05       200.75
3           3  Alice Johnson  789 Pine St  2024-01-15       300.00

### TASK 3:
1. Group the DataFrame by the Region column
2. Calculate the total Sales for each region
3. Calculate the average Sales for each region
4. Print the resulting DataFrame

### Create a sample DataFrame
data = {  
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],  
    'Sales': [150, 200, 250, 300, 350, 400, 450, 500],  
    'Quarter': ['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2', 'Q2']  
}

In [51]:
data = {  
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],  
    'Sales': [150, 200, 250, 300, 350, 400, 450, 500],  
    'Quarter': ['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2', 'Q2']  
}

df = pd.DataFrame(data)
df

  Region  Sales Quarter
0  North    150      Q1
1  South    200      Q1
2   East    250      Q1
3   West    300      Q1
4  North    350      Q2
5  South    400      Q2
6   East    450      Q2
7   West    500      Q2

In [52]:
grouped_df = df.groupby('Region')['Sales'].agg(Total_sales = 'sum', Average_Sales = 'mean')
grouped_df

        Total_sales  Average_Sales
Region
East            700          350.0
North           500          250.0
South           600          300.0
West            800          400.0