## **Panda and Numpy Tasks**

### **Pandas**

### TASK 1:

1. Filter the DataFrame to only include rows where the Price is greater than $50
2. Filter the resulting DataFrame to only include rows where the Category is either "Electronics" or "Fashion"
3. Print the resulting DataFrame

### Create the sample DataFrame dataframe
data = {  
    'Product': ['Laptop', 'Shirt', 'Smartphone', 'Shoes', 'Headphones', 'Watch'],  
    'Price': [999.99, 29.99, 599.99, 89.99, 199.99, 49.99],  
    'Category': ['Electronics', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion']  
}

In [120]:
#use dataframe1 as name of dataframe
import pandas as pd
data = {  
    'Product': ['Laptop', 'Shirt', 'Smartphone', 'Shoes', 'Headphones', 'Watch'],  
    'Price': [999.99, 29.99, 599.99, 89.99, 199.99, 49.99],  
    'Category': ['Electronics', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion']  
}
dataframe1 = pd.DataFrame(data)    
dataframe1

      Product   Price     Category
0      Laptop  999.99  Electronics
1       Shirt   29.99      Fashion
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics
5       Watch   49.99      Fashion

In [121]:
dataframe_50 = dataframe1[dataframe1["Price"] > 50]
dataframe_50

      Product   Price     Category
0      Laptop  999.99  Electronics
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics

In [122]:
condition = dataframe_50["Category"].isin(["Electronics", "Fashion"])
dataframe_EF = dataframe_50[condition]
dataframe_EF

      Product   Price     Category
0      Laptop  999.99  Electronics
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics

### TASK 2:

1. Merge the two DataFrames on the CustomerID column
2. Print the resulting DataFrame
   
### Create the first sample DataFrame df1
data1 = {
    'CustomerID': [1, 2, 3, 4],
    'Name': ['John Doe', 'Jane Smith', 'Alice Johnson', 'Bob Brown'],
    'Address': ['123 Elm St', '456 Oak St', '789 Pine St', '101 Maple St']
}

### Create the second sample DataFrame df2
data2 = {
    'CustomerID': [1, 2, 1, 3],  
    'OrderDate': ['2024-01-01', '2024-01-05', '2024-01-10', '2024-01-15'],  
    'TotalAmount': [100.50, 200.75, 150.25, 300.00]  
}

In [123]:
#use dataframe2 and dataframe3 as name of dataframe
data1 = {
    'CustomerID': [1, 2, 3, 4],
    'Name': ['John Doe', 'Jane Smith', 'Alice Johnson', 'Bob Brown'],
    'Address': ['123 Elm St', '456 Oak St', '789 Pine St', '101 Maple St']
}

data2 = {
    'CustomerID': [1, 2, 1, 3],  
    'OrderDate': ['2024-01-01', '2024-01-05', '2024-01-10', '2024-01-15'],  
    'TotalAmount': [100.50, 200.75, 150.25, 300.00]  
}

dataframe2 = pd.DataFrame(data1)
dataframe3 = pd.DataFrame(data2)

In [124]:
merged_dataframe = pd.merge(dataframe2, dataframe3, on='CustomerID')
merged_dataframe

   CustomerID           Name      Address   OrderDate  TotalAmount
0           1       John Doe   123 Elm St  2024-01-01       100.50
1           1       John Doe   123 Elm St  2024-01-10       150.25
2           2     Jane Smith   456 Oak St  2024-01-05       200.75
3           3  Alice Johnson  789 Pine St  2024-01-15       300.00

### TASK 3:
1. Group the DataFrame by the Region column
2. Calculate the total Sales for each region
3. Calculate the average Sales for each region
4. Print the resulting DataFrame

### Create a sample DataFrame
data = {  
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],  
    'Sales': [150, 200, 250, 300, 350, 400, 450, 500],  
    'Quarter': ['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2', 'Q2']  
}

In [125]:
data = {  
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],  
    'Sales': [150, 200, 250, 300, 350, 400, 450, 500],  
    'Quarter': ['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2', 'Q2']  
}
dataframe = pd.DataFrame(data)
dataframe_byreg = dataframe.groupby("Region")
dataframe_byreg

In [126]:
df_sales = dataframe_byreg["Sales"].sum()
df_sales

Region
East     700
North    500
South    600
West     800
Name: Sales, dtype: int64

In [127]:
df_avgsales = dataframe_byreg["Sales"].mean()

In [128]:
df_avgsales

Region
East     350.0
North    250.0
South    300.0
West     400.0
Name: Sales, dtype: float64

## TASK 4

Create an empty data dictionary with keys: name, roll, address, age where all the keys store a list of values. Fill in 10 valid data samples in the dictionary asking from the user. Then convert the dictionary to dataframe and add a new column to the dataframe called ‘category’. If the age is less than or equal to 15 then, category will be ‘Junior’, if its between 15 to 25(included), category will be ‘Mid’ and for the rest - category will be ‘Senior’. Display the dataframe. Calculate the average age and most frequent category.

**Data**

Aayush Sharma,101,Kathmandu,14

Sneha Thapa,102,Pokhara,18

Ramesh Koirala,103,Biratnagar,22

Priya Adhikari,104,Lalitpur,26

Nitesh Bhandari,105,Butwal,24

Anjali Shrestha,106,Bhaktapur,15

Suman KC,107,Dharan,30

Bina Lama,108,Hetauda,12

Roshan Giri,109,Nepalgunj,27

Kritika Maharjan,110,Janakpur,20

In [129]:
import pandas as pd
information = ["Aayush Sharma,101,Kathmandu,14",

"Sneha Thapa,102,Pokhara,18",

"Ramesh Koirala,103,Biratnagar,22",

"Priya Adhikari,104,Lalitpur,26",

"Nitesh Bhandari,105,Butwal,24",

"Anjali Shrestha,106,Bhaktapur,15",

"Suman KC,107,Dharan,30",

"Bina Lama,108,Hetauda,12",

"Roshan Giri,109,Nepalgunj,27",

"Kritika Maharjan,110,Janakpur,20"]

def predefined_input():
    data = []
    for i in range(10):
        name, roll, address, age = information[i].split(",")

        student = {
            "name": name,
            "roll": roll,
            "address": address,
            "age": age
        }

        data.append(student)

    return data

In [130]:
def user_input():
    data = []
    while True:
        user_input = input("Enter name, roll, address, age: ")

        if user_input == "esc":
            break

        name, roll, address, age = user_input.split(",")

        student = {
            "name": name,
            "roll": roll,
            "address": address,
            "age": age
        }
        data.append(student)

    return data

In [131]:
data_one = predefined_input()
dataframe_one = pd.DataFrame(data_one)
dataframe_one

               name roll     address age
0     Aayush Sharma  101   Kathmandu  14
1       Sneha Thapa  102     Pokhara  18
2    Ramesh Koirala  103  Biratnagar  22
3    Priya Adhikari  104    Lalitpur  26
4   Nitesh Bhandari  105      Butwal  24
5   Anjali Shrestha  106   Bhaktapur  15
6          Suman KC  107      Dharan  30
7         Bina Lama  108     Hetauda  12
8       Roshan Giri  109   Nepalgunj  27
9  Kritika Maharjan  110    Janakpur  20

In [132]:
data_two = user_input()
dataframe_two = pd.DataFrame(data_two)
dataframe_two

Empty DataFrame
Columns: []
Index: []

In [133]:
# Grouping
dataframe_one["age"] = dataframe_one["age"].astype(int)

def categorize(age: int):
    if age < 15:
        return 'junior'
    elif( age > 15) & (age <= 25):
        return 'mid'
    else:
        return 'senior'
    
dataframe_one["category"] = dataframe_one["age"].apply(categorize)

dataframe_one

               name roll     address  age category
0     Aayush Sharma  101   Kathmandu   14   junior
1       Sneha Thapa  102     Pokhara   18      mid
2    Ramesh Koirala  103  Biratnagar   22      mid
3    Priya Adhikari  104    Lalitpur   26   senior
4   Nitesh Bhandari  105      Butwal   24      mid
5   Anjali Shrestha  106   Bhaktapur   15   senior
6          Suman KC  107      Dharan   30   senior
7         Bina Lama  108     Hetauda   12   junior
8       Roshan Giri  109   Nepalgunj   27   senior
9  Kritika Maharjan  110    Janakpur   20      mid

In [134]:
avg_age = dataframe_one["age"].mean()
print(f"Average age in dataframe: {avg_age}")

Average age in dataframe: 20.8

In [135]:
most_freq = dataframe_one["category"].mode()[0]
print(f"The most frequent category is: {most_freq}")

The most frequent category is: mid

### **Numpy**

In [136]:
# Task 1:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# From a, select elements that are divisible by 2
div2 = a[a % 2 == 0]
div2

array([ 2,  4,  6,  8, 10, 12])

In [137]:
# From a, select elements that are greater than 2 and less than or equal to 10
sel = a[(a > 2) & (a <= 10)]
sel

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [138]:
# Task 2: 
data = np.array([1,2])
ones = np.ones(2)

# Perform subtraction, multiplication, division
sub = data - ones
mul = data * data
div = data / data

print(f"Data: {data}, Ones: {ones}\nSubtraction: {sub}\tMultiplication: {mul}\tDivision: {div}")

Data: [1 2], Ones: [1. 1.]
Subtraction: [0. 1.]	Multiplication: [1 4]	Division: [1. 1.]

In [139]:
# Use aggregation
data_new = np.array([22, 6, 9, 10])

print(f"Data: {data_new}\nMax: {data_new.max()}\nMin: {data_new.min()}\nSum: {data_new.sum()}")

Data: [22  6  9 10]
Max: 22
Min: 6
Sum: 47

In [140]:
# Task 3:
matrix = np.array([[1,2], [3,4], [5,6]])

# Finding elements at specific coordinates
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [141]:
# Select 2
matrix[0,1]

np.int64(2)

In [142]:
# Select 3 through 6
matrix[1:, :]

array([[3, 4],
       [5, 6]])

In [143]:
# Select 1 and 3
matrix[:2, 0]

array([1, 3])

In [144]:
# Task 4:

# Find unique values, indices and count for 2D array

arr2d = np.array([
    [1, 2, 3, 4, 2],
    [5, 6, 7, 8, 6],
    [1, 2, 3, 4, 2],  
    [9, 10, 11, 12, 10],
    [5, 6, 7, 8, 6],   
    [13, 14, 15, 16, 14]
])

uniques, unique_idx = np.unique(arr2d, return_index=True) # Flattened
print(f"Unique Values: {uniques}\nIndices: {unique_idx}")

Unique Values: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Indices: [ 0  1  2  3  5  6  7  8 15 16 17 18 25 26 27 28]

In [145]:
# Using an axis
uniques, unique_idx, unique_count = np.unique(arr2d, return_counts=True, return_index=True, axis=0) 
print(f"Unique Values: {uniques}\nIndices: {unique_idx}\nCount: {unique_count}\n")

uniques, unique_idx = np.unique(arr2d, return_index=True, axis=1) 
print(f"Unique Values: {uniques}\nIndices: {unique_idx}")

Unique Values: [[ 1  2  3  4  2]
 [ 5  6  7  8  6]
 [ 9 10 11 12 10]
 [13 14 15 16 14]]
Indices: [0 1 3 5]
Count: [2 2 1 1]

Unique Values: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [13 14 15 16]]
Indices: [0 1 2 3]

In [146]:
# Task 5: 

# Flip 2nd column only
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

arr[1] = np.flip(arr[1])

arr[:, 1] = np.flip(arr[:, 1])

print(arr)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]