This is just trial wrangling process done on train.csv file of Titanic dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/home/lucifer/Documents/arc-2025/arc/ai/Adarsh-Ghimire/Data-Science/Data/train.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
## counting the survival 
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [10]:
## dropping column Cabin due to huge number of null values
df.drop('Cabin',axis=1,inplace=True)

In [11]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [15]:
## imputation by mean
mean_age = df['Age'].mean()

df['Age'] = df['Age'].fillna(value=mean_age)

mode_embarked = df['Embarked'].mode()[0]
df['Embarked']  = df['Embarked'].fillna(value=mode_embarked)

In [16]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [20]:
## transforming the non-numeric values into numeric values
categorical_columns = df.dtypes[df.dtypes == 'object'].index

In [21]:
categorical_columns

Index(['Name', 'Sex', 'Ticket', 'Embarked'], dtype='object')

In [22]:
for category in categorical_columns:
    print(f"Number of unique values in {category} = {len(df[category].unique())}")

Number of unique values in Name = 891
Number of unique values in Sex = 2
Number of unique values in Ticket = 681
Number of unique values in Embarked = 3

In [23]:
## dropping Name and Ticket because transforming them into numeric by various technique introduce computational complexity 
df_cleaned = df.drop(['Name','Ticket'],axis=1)

In [24]:
df_cleaned.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [25]:
df_cleaned.shape

(891, 9)

In [26]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Fare         891 non-null    float64
 8   Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB

In [27]:
categorical_variables = df_cleaned.dtypes[df_cleaned.dtypes == 'object'].index
categorical_variables

Index(['Sex', 'Embarked'], dtype='object')

In [28]:
df_cleaned_encoded = pd.get_dummies(df_cleaned,columns=categorical_variables)
df_cleaned_encoded

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,22.000000,1,0,7.2500,False,True,False,False,True
1,2,1,1,38.000000,1,0,71.2833,True,False,True,False,False
2,3,1,3,26.000000,0,0,7.9250,True,False,False,False,True
3,4,1,1,35.000000,1,0,53.1000,True,False,False,False,True
4,5,0,3,35.000000,0,0,8.0500,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,27.000000,0,0,13.0000,False,True,False,False,True
887,888,1,1,19.000000,0,0,30.0000,True,False,False,False,True
888,889,0,3,29.699118,1,2,23.4500,True,False,False,False,True
889,890,1,1,26.000000,0,0,30.0000,False,True,True,False,False
890,891,0,3,32.000000,0,0,7.7500,False,True,False,True,False

In [29]:
df_cleaned_encoded.shape

(891, 12)

In [31]:
## applying LabelEncoder technique to column with small different values
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_copy = df_cleaned.copy()

df_copy['Sex'] = label_encoder.fit_transform(df_copy['Sex'])
print(df_copy.head())

   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    1  22.0      1      0   7.2500        S
1            2         1       1    0  38.0      1      0  71.2833        C
2            3         1       3    0  26.0      0      0   7.9250        S
3            4         1       1    0  35.0      1      0  53.1000        S
4            5         0       3    1  35.0      0      0   8.0500        S

In [32]:
df_cleaned_encoded.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Sex_female     0
Sex_male       0
Embarked_C     0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [34]:
df_cleaned_encoded.to_csv('./cleaned_dataset.csv')

#### Data Wrangling on Superstore dataset

In [40]:
new_df = pd.read_csv('arc/ai/Adarsh-Ghimire/Data-Science/Data/Superstore.csv',encoding='latin1')
new_df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [42]:
new_df.shape

(9994, 21)

In [43]:
new_df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [44]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [45]:
new_df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

No null values

In [46]:
new_df.duplicated().sum()

np.int64(0)

In [47]:
## dropping column row id because it is not necessary
new_df = new_df.drop('Row ID',axis=1)

In [48]:
new_df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [49]:
column_names = new_df.columns
column_names

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [50]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Order Date     9994 non-null   object
 2   Ship Date      9994 non-null   object
 3   Ship Mode      9994 non-null   object
 4   Customer ID    9994 non-null   object
 5   Customer Name  9994 non-null   object
 6   Segment        9994 non-null   object
 7   Country        9994 non-null   object
 8   City           9994 non-null   object
 9   State          9994 non-null   object
 10  Postal Code    9994 non-null   int64
 11  Region         9994 non-null   object
 12  Product ID     9994 non-null   object
 13  Category       9994 non-null   object
 14  Sub-Category   9994 non-null   object
 15  Product Name   9994 non-null   object
 16  Sales          9994 non-null   float64
 17  Quantity       9994 non-null   int64
 18  Discount       9994 non-null   float64
 19  Profit         9994 non-null   float64
dtypes: float64(3), int64(2), object(15)
memory usage: 1.5+ MB

We can see here that most of the data in the dataframe is not numeric

In [51]:
categorical_var = new_df.dtypes[new_df.dtypes == 'object'].index
categorical_var

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name'],
      dtype='object')

In [52]:
## now finding the number of unique values for each categorical values
for category in categorical_var:
    print(f"Number of unique values in {category} = {len(new_df[category].unique())}")

Number of unique values in Order ID = 5009
Number of unique values in Order Date = 1237
Number of unique values in Ship Date = 1334
Number of unique values in Ship Mode = 4
Number of unique values in Customer ID = 793
Number of unique values in Customer Name = 793
Number of unique values in Segment = 3
Number of unique values in Country = 1
Number of unique values in City = 531
Number of unique values in State = 49
Number of unique values in Region = 4
Number of unique values in Product ID = 1862
Number of unique values in Category = 3
Number of unique values in Sub-Category = 17
Number of unique values in Product Name = 1850

Here we can see that various columns like Order ID, Order Date, Ship Date, Customer ID,Customer Name,City,State,Product ID ,Sub-Category, Product Name have large number of distinct values , one-hot encoding will not be efficient. So for that we will drop these columns and along with it here we see that Country column consists of only USA so we will drop it too.

In [58]:
new_df_cleaned = new_df.drop(["Order ID", "Order Date", "Ship Date", "Customer ID", "Customer Name", "City", "State", "Product ID", "Sub-Category", "Product Name","Country"], axis=1)

In [59]:
new_df_cleaned.head()

,Ship Mode,Segment,Postal Code,Region,Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,42420,South,Furniture,261.9600,2,0.00,41.9136
1,Second Class,Consumer,42420,South,Furniture,731.9400,3,0.00,219.5820
2,Second Class,Corporate,90036,West,Office Supplies,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,33311,South,Furniture,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,33311,South,Office Supplies,22.3680,2,0.20,2.5164

In [60]:
new_df_cleaned.shape

(9994, 9)

In [61]:
categorical_var = new_df_cleaned.dtypes[new_df_cleaned.dtypes == 'object'].index
categorical_var

Index(['Ship Mode', 'Segment', 'Region', 'Category'], dtype='object')

In [63]:
new_df_cleaned_encoded = pd.get_dummies(new_df_cleaned,columns=categorical_var,drop_first=True)
new_df_cleaned_encoded

,Postal Code,Sales,Quantity,Discount,Profit,Ship Mode_Same Day,Ship Mode_Second Class,Ship Mode_Standard Class,Segment_Corporate,Segment_Home Office,Region_East,Region_South,Region_West,Category_Office Supplies,Category_Technology
0,42420,261.9600,2,0.00,41.9136,False,True,False,False,False,False,True,False,False,False
1,42420,731.9400,3,0.00,219.5820,False,True,False,False,False,False,True,False,False,False
2,90036,14.6200,2,0.00,6.8714,False,True,False,True,False,False,False,True,True,False
3,33311,957.5775,5,0.45,-383.0310,False,False,True,False,False,False,True,False,False,False
4,33311,22.3680,2,0.20,2.5164,False,False,True,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,33180,25.2480,3,0.20,4.1028,False,True,False,False,False,False,True,False,False,False
9990,92627,91.9600,2,0.00,15.6332,False,False,True,False,False,False,False,True,False,False
9991,92627,258.5760,2,0.20,19.3932,False,False,True,False,False,False,False,True,False,True
9992,92627,29.6000,4,0.00,13.3200,False,False,True,False,False,False,False,True,True,False
9993,92683,243.1600,2,0.00,72.9480,False,True,False,False,False,False,False,True,True,False

In [66]:
## label encoding 
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
new_df_copy = new_df_cleaned.copy()

new_df_copy['Ship Mode'] = label_encoder.fit_transform(new_df_copy['Ship Mode'])
new_df_copy.head()

,Ship Mode,Segment,Postal Code,Region,Category,Sales,Quantity,Discount,Profit
0,2,Consumer,42420,South,Furniture,261.9600,2,0.00,41.9136
1,2,Consumer,42420,South,Furniture,731.9400,3,0.00,219.5820
2,2,Corporate,90036,West,Office Supplies,14.6200,2,0.00,6.8714
3,3,Consumer,33311,South,Furniture,957.5775,5,0.45,-383.0310
4,3,Consumer,33311,South,Office Supplies,22.3680,2,0.20,2.5164

In [68]:
## Saving the cleaned dataset
new_df_cleaned_encoded.to_csv("./Superstore_cleaned.csv",index=False)