In [2]:
import pandas as pd

In [3]:
data = {
    "name": [],
    "roll": [],
    "address": [],
    "age": []
}

In [5]:
## taking input from user
for i in range(10):
    print(f"Enter detail for student {i + 1}:")
    name = input("Enter name: ")
    roll = input("Enter roll number: ")
    address = input("Enter address: ")
    age = input("Enter age: ")
    print("\n")
    print(f"Entered name for student {i + 1} is {name}")
    print(f"Entered roll number for student {i + 1} is {roll}")
    print(f"Entered address for student {i + 1} is {address}")
    print(f"Entered age for student {i + 1} is {age}")
    print("\n")
    data["name"].append(name)
    data["roll"].append(roll)
    data["address"].append(address)
    data["age"].append(age)

Enter detail for student 1:


Entered name for student 1 is John
Entered roll number for student 1 is 1
Entered address for student 1 is Kathmandu
Entered age for student 1 is 20


Enter detail for student 2:


Entered name for student 2 is Ram
Entered roll number for student 2 is 2
Entered address for student 2 is Pokhara
Entered age for student 2 is 19


Enter detail for student 3:


Entered name for student 3 is Shyam
Entered roll number for student 3 is 3
Entered address for student 3 is Butwal
Entered age for student 3 is 25


Enter detail for student 4:


Entered name for student 4 is Hari
Entered roll number for student 4 is 4
Entered address for student 4 is Lalitpur
Entered age for student 4 is 35


Enter detail for student 5:


Entered name for student 5 is Adarsh
Entered roll number for student 5 is 5
Entered address for student 5 is Gulmi
Entered age for student 5 is 23


Enter detail for student 6:


Entered name for student 6 is Hanuman
Entered roll number for student 6 is 6
Entered address for student 6 is Sri Lanka
Entered age for student 6 is 100


Enter detail for student 7:


Entered name for student 7 is Sita
Entered roll number for student 7 is 8
Entered address for student 7 is Dharan
Entered age for student 7 is 16


Enter detail for student 8:


Entered name for student 8 is Ashish
Entered roll number for student 8 is 19
Entered address for student 8 is Palpa
Entered age for student 8 is 27


Enter detail for student 9:


Entered name for student 9 is Asmita
Entered roll number for student 9 is 23
Entered address for student 9 is USA
Entered age for student 9 is 38


Enter detail for student 10:


Entered name for student 10 is KN
Entered roll number for student 10 is 55
Entered address for student 10 is Nepalgunj
Entered age for student 10 is 19

In [6]:
df = pd.DataFrame(data)

In [12]:
df_cleaned = df.drop_duplicates().reset_index(drop=True)
df_cleaned

      name roll    address  age
0     John    1  Kathmandu   20
1      Ram    2    Pokhara   19
2    Shyam    3     Butwal   25
3     Hari    4   Lalitpur   35
4   Adarsh    5      Gulmi   23
5  Hanuman    6  Sri Lanka  100
6     Sita    8     Dharan   16
7   Ashish   19      Palpa   27
8   Asmita   23        USA   38
9       KN   55  Nepalgunj   19

In [17]:
## adding category column based on age

def categorize_age(age):
    if age <= 15:
        return 'Junior' 
    elif age <= 25:
        return 'Mid'
    else:
        return 'Senior'

In [19]:
df_cleaned['age'] = df_cleaned['age'].astype(int)

In [20]:
df_cleaned['category'] = df_cleaned['age'].apply(categorize_age)

In [21]:
df_cleaned

      name roll    address  age category
0     John    1  Kathmandu   20      Mid
1      Ram    2    Pokhara   19      Mid
2    Shyam    3     Butwal   25      Mid
3     Hari    4   Lalitpur   35   Senior
4   Adarsh    5      Gulmi   23      Mid
5  Hanuman    6  Sri Lanka  100   Senior
6     Sita    8     Dharan   16      Mid
7   Ashish   19      Palpa   27   Senior
8   Asmita   23        USA   38   Senior
9       KN   55  Nepalgunj   19      Mid

In [22]:
## calculating average age
average_age = df_cleaned['age'].mean()
print(f"The average age of the students is: {average_age:.2f}")

The average age of the students is: 32.20

In [25]:
## most frequent category
most_frequent_category = df_cleaned['category'].mode()[0]
print(f"The most frequent category is: {most_frequent_category}")

The most frequent category is: Mid