In [2]:
import pandas as pd

## TASK 1: <br>
a) Filter the DataFrame to only include rows where the Price is greater than $50 <br>
b) Filter the resulting DataFrame to only include rows where the Category is either "Electronics" or "Fashion" <br>
c) Print the resulting DataFrame

In [5]:
data = {
'Product': ['Laptop', 'Shirt', 'Smartphone', 'Shoes', 'Headphones', 'Watch'],
'Price': [999.99, 29.99, 599.99, 89.99, 199.99, 49.99],
'Category': ['Electronics', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion']
}
df = pd.DataFrame(data)
df.head()

      Product   Price     Category
0      Laptop  999.99  Electronics
1       Shirt   29.99      Fashion
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics

In [ ]:
#a
df = df[df['Price']>50]

      Product   Price     Category
0      Laptop  999.99  Electronics
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics

In [ ]:
#b
df = df[(df['Category'].isin(['Electronics','Fashion']))]
# or df[(df['Category'] == 'Electronics') | (df['Category'] == 'Fashion')]

      Product   Price     Category
0      Laptop  999.99  Electronics
1       Shirt   29.99      Fashion
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics
5       Watch   49.99      Fashion

In [18]:
df.head()

      Product   Price     Category
0      Laptop  999.99  Electronics
1       Shirt   29.99      Fashion
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics


## TASK 2:
a) Merge the two DataFrames on the CustomerID column <br>
b) Print the resulting DataFrame <br>

In [19]:
data1 = { 'CustomerID': [1, 2, 3, 4], 'Name': ['John Doe', 'Jane Smith', 'Alice Johnson', 'Bob Brown'], 'Address': ['123 Elm St', '456 Oak St', '789 Pine St', '101 Maple St'] }
data2 = { 'CustomerID': [1, 2, 1, 3],
'OrderDate': ['2024-01-01', '2024-01-05', '2024-01-10', '2024-01-15'],
'TotalAmount': [100.50, 200.75, 150.25, 300.00]
}

In [20]:
df1= pd.DataFrame(data1)
df1.head()

   CustomerID           Name       Address
0           1       John Doe    123 Elm St
1           2     Jane Smith    456 Oak St
2           3  Alice Johnson   789 Pine St
3           4      Bob Brown  101 Maple St

In [21]:
df2= pd.DataFrame(data2)
df2.head()

   CustomerID   OrderDate  TotalAmount
0           1  2024-01-01       100.50
1           2  2024-01-05       200.75
2           1  2024-01-10       150.25
3           3  2024-01-15       300.00

In [22]:
merged_df = pd.merge(df1,df2,on='CustomerID')
merged_df

   CustomerID           Name      Address   OrderDate  TotalAmount
0           1       John Doe   123 Elm St  2024-01-01       100.50
1           1       John Doe   123 Elm St  2024-01-10       150.25
2           2     Jane Smith   456 Oak St  2024-01-05       200.75
3           3  Alice Johnson  789 Pine St  2024-01-15       300.00


## TASK 3:
a) Group the DataFrame by the Region column <br>
b) Calculate the total Sales for each region <br>
c) Calculate the average Sales for each region <br>
d) Print the resulting DataFrame

In [23]:
data = {
'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
'Sales': [150, 200, 250, 300, 350, 400, 450, 500],
'Quarter': ['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2', 'Q2']
}

In [27]:
df = pd.DataFrame(data)
df.head()

  Region  Sales Quarter
0  North    150      Q1
1  South    200      Q1
2   East    250      Q1
3   West    300      Q1
4  North    350      Q2

In [33]:
grouped = df.groupby('Region')['Sales'].agg(Total_sales = 'sum',Average_Sales = 'mean')
grouped.head()

        Total_sales  Average_Sales
Region
East            700          350.0
North           500          250.0
South           600          300.0
West            800          400.0

## Additional Assignment

Create an empty data dictionary with keys: name, roll, address, age where all the keys store a list of values. Fill in 10 valid data samples in the dictionary asking from the user. Then convert the dictionary to dataframe and add a new column to the dataframe called ‘category’. If the age is less than or equal to 15 then, category will be ‘Junior’, if its between 15 to 25(included), category will be ‘Mid’ and for the rest - category will be ‘Senior’. Display the dataframe. Calculate the average age and most frequent category.

In [36]:
#initializing dictionary
data = {
    'name':[],
    'roll':[],
    'address':[],
    'age':[]
}

In [38]:
#filling in values 
for i in range(10):
    name = input(f"Enter name of {i+1} student:")
    roll = int(input(f"Enter roll of {i+1} student:"))
    address = input(f"Enter address of {i+1} student:")
    age = int(input(f"Enter age of {i+1} student:"))

    data['name'].append(name)
    data['roll'].append(roll)
    data['address'].append(address)
    data['age'].append(age)

In [42]:
data.values()

dict_values([['ram', 'shyam', 'hari', 'steve', 'peter', 'resham', 'aashish', 'alok', 'brijesh', 'saman'], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], ['bkt', 'ktm', 'btwl', 'udy', 'aus', 'dolpa]', 'surkhet', 'udaypur', 'ktm', 'bkt'], [20, 34, 32, 21, 25, 22, 23, 23, 22, 32]])

In [43]:
df = pd.DataFrame(data)
df.head()

    name  roll address  age
0    ram     1     bkt   20
1  shyam     2     ktm   34
2   hari     3    btwl   32
3  steve     4     udy   21
4  peter     5     aus   25

In [44]:
#categorize 
def categorize(age):
    if age <= 15:
        return 'Junior'
    elif 15 < age <= 25:
        return 'Mid'
    else:
        return 'Senior'
    
df['category'] = df['age'].apply(categorize)
df.head()

    name  roll address  age category
0    ram     1     bkt   20      Mid
1  shyam     2     ktm   34   Senior
2   hari     3    btwl   32   Senior
3  steve     4     udy   21      Mid
4  peter     5     aus   25      Mid

In [45]:
#Calculate average age
average_age = df['age'].mean()
print(average_age)

25.4

In [50]:
# Find the most frequent category
most_freq_cat = df['category'].mode()[0]
most_freq_cat

'Mid'