In [ ]:
%%capture
import os
if "COLAB_" not in "".join(os.environ.keys()):
    !pip install unsloth
else:
    # Do this only in Colab notebooks! Otherwise use pip install unsloth
    !pip install --no-deps bitsandbytes accelerate xformers==0.0.29.post3 peft trl triton cut_cross_entropy unsloth_zoo
    !pip install sentencepiece protobuf "datasets>=3.4.1" huggingface_hub hf_transfer
    !pip install --no-deps unsloth

### Unsloth

In [ ]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # # Set the maximum input length (in tokens) that the model can process
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/Meta-Llama-3.1-8B-bnb-4bit",      # Llama-3.1 2x faster
    "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit",
    "unsloth/Meta-Llama-3.1-70B-bnb-4bit",
    "unsloth/Meta-Llama-3.1-405B-bnb-4bit",    # 4bit for 405b!
    "unsloth/Mistral-Small-Instruct-2409",     # Mistral 22b 2x faster!
    "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
    "unsloth/Phi-3.5-mini-instruct",           # Phi-3.5 2x faster!
    "unsloth/Phi-3-medium-4k-instruct",
    "unsloth/gemma-2-9b-bnb-4bit",
    "unsloth/gemma-2-27b-bnb-4bit",            # Gemma 2x faster!

    "unsloth/Llama-3.2-1B-bnb-4bit",           # NEW! Llama 3.2 models
    "unsloth/Llama-3.2-1B-Instruct-bnb-4bit",
    "unsloth/Llama-3.2-3B-bnb-4bit",
    "unsloth/Llama-3.2-3B-Instruct-bnb-4bit",

    "unsloth/Llama-3.3-70B-Instruct-bnb-4bit" # NEW! Llama 3.3 70B!
] # These models are quantized to 4-bit, which helps reduce GPU memory usage dramatically.
# Models ending with `Instruct` are fine-tuned to follow instructions better.

model, tokenizer = FastLanguageModel.from_pretrained( # This loads the model and tokenizer ready for inference or fine-tuning.
    model_name = "unsloth/Llama-3.2-3B-Instruct", # or choose "unsloth/Llama-3.2-1B-Instruct"
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    # token = "hf_...", # use one if using gated models like meta-llama/Llama-2-7b-hf
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2025.6.2: Fast Llama patching. Transformers: 4.52.4.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 7.5. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/2.35G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/234 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/54.7k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/3.83k [00:00<?, ?B/s]

In [ ]:
print("Model config:\n", model.config)
print("Tokenizer vocab size:", tokenizer.vocab_size)
print("Tokenized example:", tokenizer("Solve 23 + 19 step by step."))

Model config:
 LlamaConfig {
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 128000,
  "eos_token_id": 128009,
  "head_dim": 128,
  "hidden_act": "silu",
  "hidden_size": 3072,
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "max_position_embeddings": 131072,
  "mlp_bias": false,
  "model_type": "llama",
  "num_attention_heads": 24,
  "num_hidden_layers": 28,
  "num_key_value_heads": 8,
  "pad_token_id": 128004,
  "pretraining_tp": 1,
  "quantization_config": {
    "bnb_4bit_compute_dtype": "float16",
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_use_double_quant": true,
    "llm_int8_enable_fp32_cpu_offload": false,
    "llm_int8_has_fp16_weight": false,
    "llm_int8_skip_modules": null,
    "llm_int8_threshold": 6.0,
    "load_in_4bit": true,
    "load_in_8bit": false,
    "quant_method": "bitsandbytes"
  },
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "factor": 32.0,
    "high_freq_factor": 4.0,
    "low_freq_factor": 1.0,
    "original_max_position_embeddings": 8192,
    "rope_type": "llama3"
  },
  "rope_theta": 500000.0,
  "tie_word_embeddings": true,
  "torch_dtype": "float16",
  "transformers_version": "4.52.4",
  "unsloth_fixed": true,
  "unsloth_version": "2025.6.2",
  "use_cache": true,
  "vocab_size": 128256
}

Tokenizer vocab size: 128000
Tokenized example: {'input_ids': [128000, 50, 4035, 220, 1419, 489, 220, 777, 3094, 555, 3094, 13], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
decoded_text = tokenizer.decode([128000, 50, 4035, 220, 1419, 489, 220, 777, 3094, 555, 3094, 13])
print(decoded_text)

<|begin_of_text|>Solve 23 + 19 step by step.

We now add LoRA adapters so we only need to update 1 to 10% of all parameters!

In [ ]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,  #  The "rank" of the LoRA update matrices A and B.
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj"],
             #  These are the layers where LoRA adapters will be injected.
             #    Common in transformer models:
             #      - q_proj, k_proj, v_proj: attention projection matrices
             #      - o_proj: output projection from attention
             #      - up/down/gate_proj: MLP layers
             #    Only these will be fine-tuned — rest of the model stays frozen.
    lora_alpha = 16,
             #  Scaling factor for the LoRA updates.Higher alpha = stronger influence.
    lora_dropout = 0,
             #  Dropout.Often set to 0 for efficiency; can use small value for regularization.
    bias = "none",
             #  Whether to train the bias terms of the model.
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
    use_rslora = False,
             #  Whether to use Rank-Stabilized LoRA.
             #    Helps prevent performance drop when using very small ranks.
             #    Set to `True` if experimenting with extremely low-rank setups (e.g., r=1).
    loftq_config = None,
             # a quantization-aware LoRA.
             #    Leave as `None` unless you specifically want quantized LoRA training.

)

Unsloth 2025.6.2 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

<a name="Data"></a>
### Data Prep
We now use the `Llama-3.1` format for conversation style finetunes. We use [Maxime Labonne's FineTome-100k](https://huggingface.co/datasets/mlabonne/FineTome-100k) dataset in ShareGPT style. But we convert it to HuggingFace's normal multiturn format `("role", "content")` instead of `("from", "value")`/ Llama-3 renders multi turn conversations like below:

```
<|begin_of_text|><|start_header_id|>user<|end_header_id|>

Hello!<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Hey there! How are you?<|eot_id|><|start_header_id|>user<|end_header_id|>

I'm great thanks!<|eot_id|>
```

We use our `get_chat_template` function to get the correct chat template. We support `zephyr, chatml, mistral, llama, alpaca, vicuna, vicuna_old, phi3, llama3` and more.

In [ ]:
from unsloth.chat_templates import get_chat_template # for prompt formating

tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3.1",
)

# Define a function to convert the dataset's raw "conversations" into a single training string
def formatting_prompts_func(examples):
    convos = examples["conversations"]  # Each item is a list of {"role": ..., "content": ...}

    # Apply the chat template to each conversation and produce a full training string
    texts = [
        tokenizer.apply_chat_template(
            convo,
            tokenize = False,             # We want raw string output here, not token IDs yet
            add_generation_prompt = False # We don't want the model to predict a response yet
        ) for convo in convos
    ]

    return { "text" : texts }  # HuggingFace Datasets expects a dict output


from datasets import load_dataset
dataset = load_dataset("mlabonne/FineTome-100k", split = "train")

README.md:   0%|          | 0.00/982 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/117M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/100000 [00:00<?, ? examples/s]

We now use `standardize_sharegpt` to convert ShareGPT style datasets into HuggingFace's generic format. This changes the dataset from looking like:
```
{"from": "system", "value": "You are an assistant"}
{"from": "human", "value": "What is 2+2?"}
{"from": "gpt", "value": "It's 4."}
```
to
```
{"role": "system", "content": "You are an assistant"}
{"role": "user", "content": "What is 2+2?"}
{"role": "assistant", "content": "It's 4."}
```

In [ ]:
from unsloth.chat_templates import standardize_sharegpt
dataset = standardize_sharegpt(dataset)
dataset = dataset.map(formatting_prompts_func, batched = True,)

Unsloth: Standardizing formats (num_proc=2):   0%|          | 0/100000 [00:00<?, ? examples/s]

Map:   0%|          | 0/100000 [00:00<?, ? examples/s]

We look at how the conversations are structured for item 5:

In [ ]:
dataset[5]["conversations"]

[{'content': 'How do astronomers determine the original wavelength of light emitted by a celestial body at rest, which is necessary for measuring its speed using the Doppler effect?',
  'role': 'user'},
 {'content': 'Astronomers make use of the unique spectral fingerprints of elements found in stars. These elements emit and absorb light at specific, known wavelengths, forming an absorption spectrum. By analyzing the light received from distant stars and comparing it to the laboratory-measured spectra of these elements, astronomers can identify the shifts in these wavelengths due to the Doppler effect. The observed shift tells them the extent to which the light has been redshifted or blueshifted, thereby allowing them to calculate the speed of the star along the line of sight relative to Earth.',
  'role': 'assistant'}]

And we see how the chat template transformed these conversations.

**[Notice]** Llama 3.1 Instruct's default chat template default adds `"Cutting Knowledge Date: December 2023\nToday Date: 26 July 2024"`, so do not be alarmed!

In [ ]:
dataset[5]["text"]

'<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nHow do astronomers determine the original wavelength of light emitted by a celestial body at rest, which is necessary for measuring its speed using the Doppler effect?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nAstronomers make use of the unique spectral fingerprints of elements found in stars. These elements emit and absorb light at specific, known wavelengths, forming an absorption spectrum. By analyzing the light received from distant stars and comparing it to the laboratory-measured spectra of these elements, astronomers can identify the shifts in these wavelengths due to the Doppler effect. The observed shift tells them the extent to which the light has been redshifted or blueshifted, thereby allowing them to calculate the speed of the star along the line of sight relative to Earth.<|eot_id|>'

<a name="Train"></a>
### Train the model
Now let's use Huggingface TRL's `SFTTrainer`! More docs here: [TRL SFT docs](https://huggingface.co/docs/trl/sft_trainer). We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`. We also support TRL's `DPOTrainer`!

In [ ]:
from trl import SFTTrainer
from transformers import TrainingArguments, DataCollatorForSeq2Seq
from unsloth import is_bfloat16_supported

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    data_collator = DataCollatorForSeq2Seq(tokenizer = tokenizer), # Batches and pads sequences correctly.
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4, #Accumulates gradients over 4 steps before updating weights.
        warmup_steps = 5, #Linearly increases learning rate over the first 5 steps.
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use this for WandB etc
    ),
)

Unsloth: Tokenizing ["text"]:   0%|          | 0/100000 [00:00<?, ? examples/s]

We also use Unsloth's `train_on_completions` method to only train on the assistant outputs and ignore the loss on the user's inputs.

In [ ]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only( # This helps avoid overfitting to the prompt structure and focuses training on generating useful responses.
    trainer,
    instruction_part = "<|start_header_id|>user<|end_header_id|>\n\n",
    response_part = "<|start_header_id|>assistant<|end_header_id|>\n\n",
)

Map:   0%|          | 0/100000 [00:00<?, ? examples/s]

We verify masking is actually done:

In [ ]:
tokenizer.decode(trainer.train_dataset[5]["input_ids"])

'<|begin_of_text|><|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nHow do astronomers determine the original wavelength of light emitted by a celestial body at rest, which is necessary for measuring its speed using the Doppler effect?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nAstronomers make use of the unique spectral fingerprints of elements found in stars. These elements emit and absorb light at specific, known wavelengths, forming an absorption spectrum. By analyzing the light received from distant stars and comparing it to the laboratory-measured spectra of these elements, astronomers can identify the shifts in these wavelengths due to the Doppler effect. The observed shift tells them the extent to which the light has been redshifted or blueshifted, thereby allowing them to calculate the speed of the star along the line of sight relative to Earth.<|eot_id|>'

In [ ]:
from transformers import DataCollatorForSeq2Seq

# Get the tokenizer-ready sample
sample = dataset[5]  # Raw 'text' field only
collator = DataCollatorForSeq2Seq(tokenizer, return_tensors="pt")

# Tokenize manually
tokenized = tokenizer(sample["text"], return_tensors="pt", max_length=2048, padding="max_length", truncation=True)

# Manually simulate label creation (copy of input_ids with user part masked)
labels = tokenized["input_ids"].clone()
# Optional: mask part of labels if you want to simulate response-only training

# Decode full input
decoded_input = tokenizer.decode(tokenized["input_ids"][0], skip_special_tokens=False)
print(" Full Input:\n", decoded_input)

# Decode labels (no -100 here unless you apply masking)
print("\n Labels (Simulated):\n", tokenizer.decode(labels[0], skip_special_tokens=False))

 Full Input:
 <|begin_of_text|><|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 July 2024

<|eot_id|><|start_header_id|>user<|end_header_id|>

How do astronomers determine the original wavelength of light emitted by a celestial body at rest, which is necessary for measuring its speed using the Doppler effect?<|eot_id|><|start_header_id|>assistant<|end_header_id|>


We can see the System and Instruction prompts are successfully masked!

In [ ]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = Tesla T4. Max memory = 14.741 GB.
3.441 GB of memory reserved.

In [ ]:
trainer_stats = trainer.train() #contains:train_runtime train_loss Token count, etc.

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 100,000 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 24,313,856/3,000,000,000 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

In [ ]:
# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
    f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

460.3077 seconds used for training.
7.67 minutes used for training.
Peak reserved memory = 4.131 GB.
Peak reserved memory for training = 0.69 GB.
Peak reserved memory % of max memory = 28.024 %.
Peak reserved memory for training % of max memory = 4.681 %.

<a name="Inference"></a>
### Inference
Let's run the model! You can change the instruction and input - leave the output blank!



We use `min_p = 0.1` and `temperature = 1.5`. Read this [Tweet](https://x.com/menhguin/status/1826132708508213629) for more information on why.

In [ ]:
from unsloth.chat_templates import get_chat_template

tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3.1",
)
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

messages = [
    {"role": "user", "content": "Continue the fibonnaci sequence: 1, 1, 2, 3, 5, 8,"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Adds the assistant prompt after the user's message for the model to continue.


    return_tensors = "pt",
).to("cuda")

outputs = model.generate(input_ids = inputs, max_new_tokens = 64, use_cache = True,
                         temperature = 1.5, min_p = 0.1)
tokenizer.batch_decode(outputs)

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

['<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nContinue the fibonnaci sequence: 1, 1, 2, 3, 5, 8,<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nThe Fibonacci sequence is a series of numbers in which each number is the sum of the two preceding numbers. The sequence you provided starts with 1, 1, 2, 3, 5, and 8. Here is how you can extend the sequence using this rule:\n\n- 1 + 1']

 You can also use a `TextStreamer` for continuous inference - so you can see the generation token by token, instead of waiting the whole time!

In [ ]:
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

messages = [
    {"role": "user", "content": "Continue the fibonnaci sequence: 1, 1, 2, 3, 5, 8,"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Must add for generation
    return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer, skip_prompt = True)
_ = model.generate(input_ids = inputs, streamer = text_streamer, max_new_tokens = 128,
                   use_cache = True, temperature = 1.5, min_p = 0.1) # Increases randomness in output. Top-p (nucleus) sampling variant called Typical Decodi

1, 1, 2, 3, 5, 8, 13<|eot_id|>

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Huggingface's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [ ]:
model.save_pretrained("lora_model")  # Local saving
tokenizer.save_pretrained("lora_model")
# model.push_to_hub("your_name/lora_model", token = "...") # Online saving
# tokenizer.push_to_hub("your_name/lora_model", token = "...") # Online saving

('lora_model/tokenizer_config.json',
 'lora_model/special_tokens_map.json',
 'lora_model/chat_template.jinja',
 'lora_model/tokenizer.json')

Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

In [ ]:
if False:
    from unsloth import FastLanguageModel
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "lora_model", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit,
    )
    FastLanguageModel.for_inference(model) # Enable native 2x faster inference

messages = [
    {"role": "user", "content": "Describe a tall tower in the capital of France."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Must add for generation
    return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer, skip_prompt = True)
_ = model.generate(input_ids = inputs, streamer = text_streamer, max_new_tokens = 128,
                   use_cache = True, temperature = 1.5, min_p = 0.1)

The tower you are referring to is the Eiffel Tower. The Eiffel Tower is a tower that is 324 meters high in the capital city of France, which is also the country's largest city and a city where people love to be. The tower is shaped like a large square, with four corners that are 2.5 meters in diameter and four square legs that are each 12.1 meters in height, as well as four sides of the legs with angles of 23.4 and 56.7 degrees and angles of 23.4 and 56.7 degrees between them.<|eot_id|>

You can also use Hugging Face's `AutoModelForPeftCausalLM`. Only use this if you do not have `unsloth` installed. It can be hopelessly slow, since `4bit` model downloading is not supported, and Unsloth's **inference is 2x faster**.

In [ ]:
if False:
    # I highly do NOT suggest - use Unsloth if possible
    from peft import AutoPeftModelForCausalLM
    from transformers import AutoTokenizer
    model = AutoPeftModelForCausalLM.from_pretrained(
        "lora_model", # YOUR MODEL YOU USED FOR TRAINING
        load_in_4bit = load_in_4bit,
    )
    tokenizer = AutoTokenizer.from_pretrained("lora_model")

### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens.

In [ ]:
# Merge to 16bit
if False: model.save_pretrained_merged("model", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "merged_16bit", token = "")

# Merge to 4bit
if False: model.save_pretrained_merged("model", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "merged_4bit", token = "")

# Just LoRA adapters
if False:
    model.save_pretrained("model")
    tokenizer.save_pretrained("model")
if False:
    model.push_to_hub("hf/model", token = "")
    tokenizer.push_to_hub("hf/model", token = "")

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [Wiki page](https://github.com/unslothai/unsloth/wiki#gguf-quantization-options)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

In [ ]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("model", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("hf/model", tokenizer, token = "")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("model", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("hf/model", tokenizer, quantization_method = "f16", token = "")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("model", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("hf/model", tokenizer, quantization_method = "q4_k_m", token = "")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "hf/model", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "", # Get a token at https://huggingface.co/settings/tokens
    )

## custom dataset

In [70]:
from unsloth.chat_templates import get_chat_template # for prompt formating

tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3.2",
)

# Define a function to convert the dataset's raw "conversations" into a single training string
def formatting_prompts_func(examples):
    convos = examples["conversations"]  # Each item is a list of {"role": ..., "content": ...}

    # Apply the chat template to each conversation and produce a full training string
    texts = [
        tokenizer.apply_chat_template(
            convo,
            tokenize = False,             # We want raw string output here, not token IDs yet
            add_generation_prompt = False # We don't want the model to predict a response yet
        ) for convo in convos
    ]

    return { "text" : texts }  # HuggingFace Datasets expects a dict output


from datasets import load_dataset
dataset = load_dataset('json', data_files='grade5_math_cot_500.jsonl', split='train')

dataset = standardize_sharegpt(dataset)
dataset = dataset.map(formatting_prompts_func, batched = True,)

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [71]:
for i in range(5):  # Show first 5 samples
    print(dataset[i])
    print("-" * 40)

{'conversations': [{'role': 'user', 'content': 'What is 24 division 5?'}, {'role': 'assistant', 'content': 'To divide 24 by 5, we do 24 ÷ 5 = 4.8'}], 'text': '<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nWhat is 24 division 5?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nTo divide 24 by 5, we do 24 ÷ 5 = 4.8<|eot_id|>'}
----------------------------------------
{'conversations': [{'role': 'user', 'content': 'What is 51 subtraction 72?'}, {'role': 'assistant', 'content': 'To subtract 72 from 51, we do 51 - 72 = -21.'}], 'text': '<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nWhat is 51 subtraction 72?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nTo subtract 72 from 51, we do 51 - 72 = -21.<|eot_id|>'}
----------------------------------------
{'conversations': [{'role': 'user', 'content': 'What is 60 subtraction 51?'}, {'role': 'assistant', 'content': 'To subtract 51 from 60, we do 60 - 51 = 9.'}], 'text': '<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nWhat is 60 subtraction 51?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nTo subtract 51 from 60, we do 60 - 51 = 9.<|eot_id|>'}
----------------------------------------
{'conversations': [{'role': 'user', 'content': 'What is 48 multiplication 33?'}, {'role': 'assistant', 'content': 'To multiply 48 and 33, we do 48 × 33 = 1584.'}], 'text': '<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nWhat is 48 multiplication 33?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nTo multiply 48 and 33, we do 48 × 33 = 1584.<|eot_id|>'}
----------------------------------------
{'conversations': [{'role': 'user', 'content': 'What is 95 subtraction 68?'}, {'role': 'assistant', 'content': 'To subtract 68 from 95, we do 95 - 68 = 27.'}], 'text': '<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nWhat is 95 subtraction 68?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nTo subtract 68 from 95, we do 95 - 68 = 27.<|eot_id|>'}
----------------------------------------

In [72]:
print(len(dataset))

500

In [73]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # # Set the maximum input length (in tokens) that the model can process
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/Llama-3.2-3B-bnb-4bit",
    "unsloth/Llama-3.2-3B-Instruct-bnb-4bit",
]

model, tokenizer = FastLanguageModel.from_pretrained( # This loads the model and tokenizer ready for inference or fine-tuning.
    model_name = "unsloth/Llama-3.2-3B-Instruct",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,

)

==((====))==  Unsloth 2025.6.2: Fast Llama patching. Transformers: 4.52.4.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 7.5. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

In [74]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(tokenizer, chat_template="llama-3.2")

from transformers import TextStreamer
FastLanguageModel.for_inference(model)  # Enable faster inference

messages = [
    {"role": "user", "content": "If I have 3 apples and buy 2 more, how many apples do I have in total?"}
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize=True,
    add_generation_prompt=True,
    return_tensors="pt"
).to("cuda")

streamer = TextStreamer(tokenizer, skip_prompt=True)
_ = model.generate(input_ids=inputs, streamer=streamer, max_new_tokens=64)

To find the total number of apples, you need to add the initial number of apples (3) to the number of apples you bought (2).

3 (initial apples) + 2 (apples bought) = 5

You now have 5 apples in total.<|eot_id|>

In [75]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,  #  The "rank" of the LoRA update matrices A and B.
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj"],
             #  These are the layers where LoRA adapters will be injected.
             #    Common in transformer models:
             #      - q_proj, k_proj, v_proj: attention projection matrices
             #      - o_proj: output projection from attention
             #      - up/down/gate_proj: MLP layers
             #    Only these will be fine-tuned — rest of the model stays frozen.
    lora_alpha = 16,
             #  Scaling factor for the LoRA updates.Higher alpha = stronger influence.
    lora_dropout = 0,
             #  Dropout.Often set to 0 for efficiency; can use small value for regularization.
    bias = "none",
             #  Whether to train the bias terms of the model.
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
    use_rslora = False,
             #  Whether to use Rank-Stabilized LoRA.
             #    Helps prevent performance drop when using very small ranks.
             #    Set to `True` if experimenting with extremely low-rank setups (e.g., r=1).
    loftq_config = None,
             # a quantization-aware LoRA.
             #    Leave as `None` unless you specifically want quantized LoRA training.

)

In [76]:
from unsloth.chat_templates import get_chat_template # for prompt formating

tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3.2",
)

# Define a function to convert the dataset's raw "conversations" into a single training string
def formatting_prompts_func(examples):
    convos = examples["conversations"]  # Each item is a list of {"role": ..., "content": ...}

    # Apply the chat template to each conversation and produce a full training string
    texts = [
        tokenizer.apply_chat_template(
            convo,
            tokenize = False,             # We want raw string output here, not token IDs yet
            add_generation_prompt = False # We don't want the model to predict a response yet
        ) for convo in convos
    ]

    return { "text" : texts }  # HuggingFace Datasets expects a dict output


from datasets import load_dataset
dataset = load_dataset("json", data_files="grade5_math_cot_500.jsonl", split="train")

In [77]:
from unsloth.chat_templates import standardize_sharegpt
dataset = standardize_sharegpt(dataset)
dataset = dataset.map(formatting_prompts_func, batched = True,)

In [78]:
dataset[5]["conversations"]

[{'role': 'user', 'content': 'What is 20 division 5?'},
 {'role': 'assistant', 'content': 'To divide 20 by 5, we do 20 ÷ 5 = 4.'}]

In [79]:
from trl import SFTTrainer
from transformers import TrainingArguments, DataCollatorForSeq2Seq
from unsloth import is_bfloat16_supported

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    data_collator = DataCollatorForSeq2Seq(tokenizer = tokenizer), # Batches and pads sequences correctly.
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4, #Accumulates gradients over 4 steps before updating weights.
        warmup_steps = 5, #Linearly increases learning rate over the first 5 steps.
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use this for WandB etc
    ),
)

In [80]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only( # This helps avoid overfitting to the prompt structure and focuses training on generating useful responses.
    trainer,
    instruction_part = "<|start_header_id|>user<|end_header_id|>\n\n",
    response_part = "<|start_header_id|>assistant<|end_header_id|>\n\n",
)

In [81]:
from transformers import DataCollatorForSeq2Seq

# Get the tokenizer-ready sample
sample = dataset[5]  # Raw 'text' field only
collator = DataCollatorForSeq2Seq(tokenizer, return_tensors="pt")

# Tokenize manually
tokenized = tokenizer(sample["text"], return_tensors="pt", max_length=2048, padding="max_length", truncation=True)

# Manually simulate label creation (copy of input_ids with user part masked)
labels = tokenized["input_ids"].clone()
# Optional: mask part of labels if you want to simulate response-only training

# Decode full input
decoded_input = tokenizer.decode(tokenized["input_ids"][0], skip_special_tokens=False)
print(" Full Input:\n", decoded_input)

# Decode labels (no -100 here unless you apply masking)
print("\n Labels (Simulated):\n", tokenizer.decode(labels[0], skip_special_tokens=False))

 Full Input:
 <|begin_of_text|><|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 July 2024

<|eot_id|><|start_header_id|>user<|end_header_id|>

What is 20 division 5?<|eot_id|><|start_header_id|>assistant<|end_header_id|>


In [82]:
trainer_stats = trainer.train() #contains:train_runtime train_loss Token count, etc.

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 500 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 24,313,856/3,000,000,000 (0.81% trained)

In [83]:
from unsloth.chat_templates import get_chat_template

tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3.2",
)
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

messages = [
    {"role": "user", "content": "What is the value for 54 subtracted from 23"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Adds the assistant prompt after the user's message for the model to continue.


    return_tensors = "pt",
).to("cuda")

outputs = model.generate(input_ids = inputs, max_new_tokens = 64, use_cache = True,
                         temperature = 1.5, min_p = 0.1)
tokenizer.batch_decode(outputs)

['<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nWhat is the value for 54 subtracted from 23<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nTo subtract 54 from 23, we do 23 - 54 = -31.<|eot_id|>']

In [84]:
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

messages = [
    {"role": "user", "content": "What is the value for 54 subtracted from 23"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Must add for generation
    return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer, skip_prompt = True)
_ = model.generate(input_ids = inputs, streamer = text_streamer, max_new_tokens = 128,
                   use_cache = True, temperature = 1.5, min_p = 0.1) # Increases randomness in output. Top-p (nucleus) sampling variant called Typical Decodi

To subtract 54 from 23, we do 23 - 54 = -31.<|eot_id|>

In [85]:
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

messages = [
    {"role": "user", "content": "If I have 3 apples and buy 2 more, how many apples do I have in total?"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Must add for generation
    return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer, skip_prompt = True)
_ = model.generate(input_ids = inputs, streamer = text_streamer, max_new_tokens = 128,
                   use_cache = True, temperature = 1.5, min_p = 0.1) # Increases randomness in output. Top-p (nucleus) sampling variant called Typical Decodi

To add 3 (the original number of apples) and 2 (the number of new apples), we simply do 3 + 2 = 5.<|eot_id|>

###  Prompt
**"I had 3 apples. I bought 2 more. How many apples do I have now?"**

---

### 🤖 Pretrained Model Response

> To find the total number of apples, you need to add the initial number of apples (3) to the number of apples you bought (2).  
>  
> 3 (initial apples) + 2 (apples bought) = 5  
>  
> You now have 5 apples in total.  
>  


---

###  Fine-Tuned Model Response

> To add 3 (the original number of apples) and 2 (the number of new apples), we simply do 3 + 2 = 5.  
>  


---

###  What This Shows

- **Pretrained model** understands the problem but explains it **passively**, more like a summary.
- **Fine-tuned model** actively **teaches** the computation by showing how to solve it step by step, which is ideal for **grade 5 educational use**.