
### TASK 1:
#### a) Filter the DataFrame to only include rows where the Price is greater than $50

#### b) Filter the resulting DataFrame to only include rows where the Category is either "Electronics" or "Fashion"

#### c) Print the resulting DataFrame

In [2]:
import pandas as pd

In [16]:
data = {
    'Product': ['Tablet', 'Wheat','Jeans', 'Camera', 'Sneakers', 'Bluetooth Speaker', 'Sunglasses','rice'],
    'Price': [499.99,80.90, 39.99, 749.99, 79.99, 19.99, 59.99, 60],
    'Category': ['Electronics','Household', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion','Household']
}

df = pd.DataFrame(data)
df.head()

    Product   Price     Category
0    Tablet  499.99  Electronics
1     Wheat   80.90    Household
2     Jeans   39.99      Fashion
3    Camera  749.99  Electronics
4  Sneakers   79.99      Fashion

In [17]:
df = df[df['Price']>50]
df

      Product   Price     Category
0      Tablet  499.99  Electronics
1       Wheat   80.90    Household
3      Camera  749.99  Electronics
4    Sneakers   79.99      Fashion
6  Sunglasses   59.99      Fashion
7        rice   60.00    Household

In [22]:
df1 = df[(df['Category'] == 'Electronics') | (df['Category'] == 'Fashion')]

In [23]:
df1.head()

      Product   Price     Category
0      Tablet  499.99  Electronics
3      Camera  749.99  Electronics
4    Sneakers   79.99      Fashion
6  Sunglasses   59.99      Fashion

### TASK 2:
##### a) Merge the two DataFrames on the CustomerID column
##### b) Print the resulting DataFrame

In [24]:
data1 = {
    'CustomerID': [5, 6, 7, 8],
    'Name': ['Sita Rai', 'Hari Sharma', 'Rita Thapa', 'Kiran Gurung'],
    'Address': ['12 Naxal Rd', '34 New Baneshwor', '56 Jawalakhel', '78 Putalisadak']
}

data2 = {
    'CustomerID': [5, 6, 5, 7],
    'OrderDate': ['2024-03-01', '2024-03-05', '2024-03-12', '2024-03-15'],
    'TotalAmount': [250.00, 175.50, 320.75, 400.00]
}

In [25]:
df1= pd.DataFrame(data1)
df1.head()

   CustomerID          Name           Address
0           5      Sita Rai       12 Naxal Rd
1           6   Hari Sharma  34 New Baneshwor
2           7    Rita Thapa     56 Jawalakhel
3           8  Kiran Gurung    78 Putalisadak

In [26]:
df2= pd.DataFrame(data2)
df2.head()

   CustomerID   OrderDate  TotalAmount
0           5  2024-03-01       250.00
1           6  2024-03-05       175.50
2           5  2024-03-12       320.75
3           7  2024-03-15       400.00

In [28]:
merge_df = pd.merge(df1,df2,on='CustomerID')

In [29]:
merge_df.head()

   CustomerID         Name           Address   OrderDate  TotalAmount
0           5     Sita Rai       12 Naxal Rd  2024-03-01       250.00
1           5     Sita Rai       12 Naxal Rd  2024-03-12       320.75
2           6  Hari Sharma  34 New Baneshwor  2024-03-05       175.50
3           7   Rita Thapa     56 Jawalakhel  2024-03-15       400.00

TASK 3:

a) Group the DataFrame by the Region column

b) Calculate the total Sales for each region

c) Calculate the average Sales for each region

d) Print the resulting DataFrame

In [30]:
data = {
    'Region': ['Central', 'Himalayan', 'Terai', 'Valley', 'Central', 'Himalayan', 'Terai', 'Valley'],
    'Sales': [180, 220, 270, 320, 370, 420, 480, 530],
    'Quarter': ['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2', 'Q2']
}

In [31]:
df = pd.DataFrame(data)
df.head()

      Region  Sales Quarter
0    Central    180      Q1
1  Himalayan    220      Q1
2      Terai    270      Q1
3     Valley    320      Q1
4    Central    370      Q2

In [32]:
grouped = df.groupby('Region')['Sales'].agg(Total_sales = 'sum',Average_Sales = 'mean')
grouped.head()

           Total_sales  Average_Sales
Region
Central            550          275.0
Himalayan          640          320.0
Terai              750          375.0
Valley             850          425.0