In [41]:
import pandas as pd

In [42]:
data = {
    "name":[],
    "roll":[],
    "address":[],
    "age":[]
    }

In [43]:
for i in range(0,10):
    data["name"].append(input("Enter the name: "))
    data["roll"].append(int(input("Enter the roll: ")))
    data["address"].append(input("Enter the address: "))
    data["age"].append(int(input("Enter the age: ")))

In [49]:
data

{'name': ['dev',
  'indra',
  'bakhati',
  'dipesh',
  'Biplop',
  'dipak',
  'bishal',
  'nimesh',
  'Raj',
  'Manish'],
 'roll': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'address': ['ktm',
  'pokhara',
  'dharan',
  'chitwan',
  'ktm',
  'okhaldhunga',
  'ktm',
  'pokhara',
  'ktm',
  'chitwan'],
 'age': [20, 26, 14, 40, 13, 30, 18, 25, 14, 30]}

In [50]:
df = pd.DataFrame(data)
df

      name  roll      address  age
0      dev     1          ktm   20
1    indra     2      pokhara   26
2  bakhati     3       dharan   14
3   dipesh     4      chitwan   40
4   Biplop     5          ktm   13
5    dipak     6  okhaldhunga   30
6   bishal     7          ktm   18
7   nimesh     8      pokhara   25
8      Raj     9          ktm   14
9   Manish    10      chitwan   30

In [51]:
a= df["age"].values
val=[]
for i in a:
    if i<=15:
        val.append("Junior")
    elif i<=25:
        val.append("Mid")
    else:
        val.append("Senior")
val

['Mid',
 'Senior',
 'Junior',
 'Senior',
 'Junior',
 'Senior',
 'Mid',
 'Mid',
 'Junior',
 'Senior']

In [52]:
df.insert(column="category",loc=0,value=val)

In [53]:
df

  category     name  roll      address  age
0      Mid      dev     1          ktm   20
1   Senior    indra     2      pokhara   26
2   Junior  bakhati     3       dharan   14
3   Senior   dipesh     4      chitwan   40
4   Junior   Biplop     5          ktm   13
5   Senior    dipak     6  okhaldhunga   30
6      Mid   bishal     7          ktm   18
7      Mid   nimesh     8      pokhara   25
8   Junior      Raj     9          ktm   14
9   Senior   Manish    10      chitwan   30

In [56]:
sum = 0
count =0
for i in df["age"]:
    sum += i
    count += 1
average_age = sum/count
print(f"Average age is: {average_age}")

Average age is: 23.0

In [77]:
value1 = df["category"].value_counts()
print(value1)

Senior    4
Mid       3
Junior    3
Name: category, dtype: int64